/* DO NOT EDIT THIS FILE - it is machine generated */
// This header file is auto-generated by the `javac -h` command.
// It defines the native methods that will be called from the Java class `org.example.NativeCracker`.

#include <jni.h>  // Include the JNI header for interacting with Java

#ifndef _Included_org_example_NativeCracker
#define _Included_org_example_NativeCracker
#ifdef __cplusplus
extern "C" {
#endif

	/*
	 * Method: crackBruteForce
	 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;
	 * This native method is called from Java to start the CUDA brute-force attack.
	 * Parameters:
	 * - jstring hash: The MD5 hash to crack
	 * - jstring charset: The character set to use
	 * - jint maxLen: The maximum password length
	 * - jstring mask: A string mask for known/unknown character positions
	 */
	JNIEXPORT jstring JNICALL Java_org_example_NativeCracker_crackBruteForce
	(JNIEnv*, jobject, jstring, jstring, jint, jstring);

	/*
	 * Method: crackDictionary
	 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
	 * This native method is called from Java to start the dictionary attack.
	 * Parameters:
	 * - jstring hash: The MD5 hash to crack
	 * - jobjectArray dictionary: An array of password guesses
	 */
	JNIEXPORT jstring JNICALL Java_org_example_NativeCracker_crackDictionary
	(JNIEnv*, jobject, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif